[package]
name = "near-rss"
version = "0.1.0"
authors = ["Nearsyh <nearsyh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.125"
feed-rs = "0.6.0"
reqwest = "0.11.3"
anyhow = "1.0"
futures = "0.3.14"

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket"

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket"