[package]
authors = ["Nearsyh <nearsyh@gmail.com>"]
edition = "2018"
name = "near-rss"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
again = "0.1.2"
anyhow = "1.0"
feed-rs = "0.6.0"
futures = "0.3.14"
reqwest = "0.11.3"
serde = "1.0.125"
sqlx = {version = "0.5", features = ["runtime-tokio-rustls", "sqlite"]}
rand = "0.8.3"
thiserror = "1.0.24"
async_once = "0.2.1"
lazy_static = "1.4.0"

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket"

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket"
